<a href="https://colab.research.google.com/github/raquelacioli/curriculo/blob/principal/Exerc%C3%ADcios_Aula_2_Numpy_Raquel_Acioli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Crie um array de 10 elementos e extraia os 5 primeiros elementos e os 5 últimos elementos

In [3]:
import numpy as np
array=np.arange(0,10)
print(array)


[0 1 2 3 4 5 6 7 8 9]


#Extraia os 5 primeiros elemento

In [7]:
primeiros_elementos=array[:5]
print(primeiros_elementos)


[0 1 2 3 4]


#Extraia os 5 últimos elemento

In [10]:
ultimos_elementos= array[-5:]
print(ultimos_elementos)

[5 6 7 8 9]


#Crie duas matrizes 2x2 e calcule a multiplicação de matrizes.

In [18]:
matriz= np.array ([[1,2],[3,4]])
matriz2=np.array([[5,6],[7,8]])
multiplicacao=np.dot(matriz,matriz2)
print(multiplicacao)

[[19 22]
 [43 50]]


#Crie dois arrays unidimensionais e concatene-os em um único array.

# Array inidimensional

In [53]:
array1=np.array([1,2,3])
print ("Array 1:")
print(array1)

Array 1:
[1 2 3]


#Cria o segundo array unidimensional

In [72]:
array2=np.array([4,5,6])
print("Array2:")
prit=(array2)


Array2:


#Concatenar os dois arrays

In [74]:
array_concatenado= np.concatenate((array1,array2))
print(f"Array concatenado:{array_concatenado}")

Array concatenado:[1 2 3 4 5 6]


 #Crie um array com 10 números aleatórios e calcule o valor máximo, mínimo e a mediana.

In [76]:
array_aleatorio=np.random.randint(10,100,10)
print("Array aleatório:")
print(array_aleatorio)

Array aleatório:
[97 16 84 60 72 15 96 19 64 86]


#Calcula o valor máximo

In [79]:
valor_maximo=np.max(array_aleatorio)
print("Valor máximo:")
print(valor_maximo)


Valor máximo:
97


#Calcule o valor mínimo

In [80]:
valor_mínimo=np.min(array_aleatorio)
print("Vaor mínimo:")
print(valor_mínimo)


Vaor mínimo:
15


#Calcule a mediana

In [81]:
mediana= np.median(array_aleatorio)
print("Mediana:")
print(mediana)

Mediana:
68.0


# Crie uma matriz 4x3 e calcule a soma de cada coluna.

#Define o número de linhas e colunas

In [11]:
import numpy as np

In [12]:
num_linhas=4
num_colunas=3

#Crie uma matriz 4x3 com números inteiros aleatórios entre 1 e 11

In [23]:
matriz = np.random.randint(1, 11, size=(num_linhas, num_colunas))
print("Matriz nova:")
print(matriz)

Matriz nova:
[[10  2  9]
 [ 8  1  5]
 [ 6  7  5]
 [ 8  2  3]]


#Crie um array com elementos duplicados e encontre os elementos únicos.

In [25]:
array_duplicado = np.array([1, 2, 2, 3, 4, 4, 5, 1, 6, 6, 6])
print("Array com elementos duplicados:")
print(array_duplicado)

Array com elementos duplicados:
[1 2 2 3 4 4 5 1 6 6 6]


#Array elementos únicos

In [28]:
array_unico=np.unique([array_duplicado])
print(array_unico)

[1 2 3 4 5 6]


Crie um array de 10 elementos e substitua todos os valores maiores que 5 por 0.

In [82]:
array_original = np.random.randint(1, 11, 10)


In [83]:
print("Array original:")
print(array_original)

Array original:
[ 3  7  7 10  4  2  9  6  7  4]


# Identifica os elementos maiores que 5 e os substitui por 0 diretamente


In [84]:
array_modificado = array_original.copy()

In [85]:
array_modificado[array_modificado > 5] = 0
print("array_modificado(valores > 5 substituídos por 0:")
print(f"array original: {array_original}")

array_modificado(valores > 5 substituídos por 0:
array original: [ 3  7  7 10  4  2  9  6  7  4]


In [40]:
print(array_modificado)

[4 0 0 1 2 0 4 5 2 0]


Crie um array de 10 números e calcule a soma acumulada.

In [51]:
array_original = np.random.randint(1, 11, 10)
print("array_original:")
print(array_original)




array_original:
[ 7  6  9  3 10  9  1  3  2  8]


In [52]:
soma_acumulada=np.cumsum(array_original)
print("Soma acumulada:")
print(soma_acumulada)


Soma acumulada:
[ 7 13 22 25 35 44 45 48 50 58]
